name: Publish Docker Image

on:
  push:
    branches: main

jobs:
  main:
    name: RT ${{ matrix.rt }} Tag ${{ matrix.tag }}
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - rt: '4.2'
            tag: '4.2'
          - rt: '4.4'
            tag: '4.4'
          - rt: '5.0'
            tag: '5.0'
          - rt: '5.0'
            tag: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push RT ${{ matrix.rt }} Tag ${{ matrix.tag }} DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.rt }}/
          file: ${{ matrix.rt }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ github.repository_owner }}/request-tracker:${{ matrix.tag }}
